### ISSUE TITLE
Downloads: confusing

### ISSUE THREAD

**Issue by mlep** [JabRef/www.jabref.org#2]
Hi,

A colleague of mine have tried to download JabRef from http://www.jabref.org .
She got confused about the available links and decided to click on install4j. Not surprisingly, she found "JabRef" (i.e. Install4j) very confusing for managing a bibliography...
2 points:
- Looking at the page, the item "Releases" looks small compared to the two others.
- Most of users are looking *only* for the last stable release.

Suggestion: above the item "Releases", add a big button similar to the one of the page https://github.com/JabRef/jabref/releases . Ideally, this button will jump directly to the sourceforge page of the last stable release.

Comment: the sourceforge download pages (e. g. http://sourceforge.net/projects/jabref/files/v3.2/JabRef_windows_3_2.exe/download ) look awful. The advertisements is covering most of the screen, asking for your email address or confusing the user to download crappy software.

**Comment by koppor** [comment]
We won't publish on sourceforge beginning with the next release. On the one hand, I'd like to support them, because they keep their platform up and running. On the other hand, the progress on their side seems to have stalled. Side note: They made their hosting software open source at the Apache Software Foundation: [Apache Allura](https://allura.apache.org/).

**Comment by mlep** [comment]
Thanks for the info about SourceForge.
I believe the Downloads section will now be clearer for users!
